// Original selected-skill practice, not complete DSKP assessment banks.
// Topic references are Ministry-authored documents; some copies are hosted by schools.
export const SCIENCE_TOPIC_SOURCES = {
  2: 'https://ecentral.my/wp-content/uploads/2024/09/DOKUMEN-PENJAJARAN_KSSR-SAINS-TAHAP-1_EDISI-3.pdf',
  4: 'https://skpktaiping.home.blog/wp-content/uploads/2019/02/dskp-kssr-semakan-2017-sains-tahun-4.pdf',
  5: 'https://asiemodel.net/wp-content/uploads/2022/08/012_DSKP_KSSR_Semakan_2017_Sains_Thn5-print.pdf',
  6: 'https://anyflip.com/qqfu/esbw/basic/51-94',
};
export const additionalScience = {
  2: [
    ['Which animal lays eggs?', 'Chicken', 'Cat|Cow|Goat', 'A chicken reproduces by laying eggs.'],
    ['Which animal gives birth to live young?', 'Cat', 'Chicken|Butterfly|Duck', 'Cats give birth to kittens.'],
    ['What does a caterpillar become after its pupa stage?', 'Butterfly', 'Tadpole|Chick|Fish', 'A butterfly develops from egg to caterpillar to pupa to adult.'],
    ['A tadpole grows into which adult animal?', 'Frog', 'Duck|Butterfly|Cat', 'A tadpole is a young frog.'],
    ['Which is needed for a bean seed to germinate?', 'Water', 'Paint|Salt crystals|Plastic wrapping', 'A bean seed needs water, air and a suitable temperature to germinate.'],
    ['What usually emerges first from a germinating bean seed?', 'Root', 'Fruit|Flower|Leaf only', 'The first root anchors the seedling and takes in water.'],
    ['Which is a source of light?', 'Lit torch', 'Unlit candle|Book|Moon', 'A lit torch produces light. The Moon reflects sunlight.'],
    ['Why can you see a book when a lamp shines on it?', 'Light from the book reaches your eyes', 'The book makes electricity|Your eyes light up the book|Sound enters your eyes', 'Light from the lamp reflects off the book into your eyes.'],
    ['What can form when an opaque object blocks light?', 'Shadow', 'Magnet|Seed|Battery', 'A shadow forms where the object blocks light.'],
    ['Which lets most light pass through?', 'Clear glass', 'Wooden board|Thick cardboard|Metal lid', 'Clear glass is transparent.'],
    ['What supplies energy in a simple torch circuit?', 'Battery', 'Plastic case only|Switch only|Empty space', 'The battery supplies electrical energy.'],
    ['A working bulb needs which circuit?', 'A complete circuit', 'A broken wire|An open switch|No battery', 'A complete conducting path allows current to flow through the bulb.'],
    ['What happens when a simple circuit switch is opened?', 'The bulb goes out', 'The bulb always gets brighter|The battery grows|The wire becomes wood', 'Opening the switch breaks the conducting path.'],
    ['Which tool measures a pencil length fairly?', 'Ruler', 'Spoon|Torch|Magnet', 'A ruler measures length using marked units.'],
    ['To compare two plant heights fairly, measure from where?', 'The same ground level', 'A different point each time|The tallest leaf only on one plant|The edge of a table', 'Using the same starting point makes the measurements comparable.'],
  ],
  4: [
    ['Which organs take in air when humans breathe?', 'Lungs', 'Stomach|Kidneys|Intestines', 'Air travels into the lungs during inhalation.'],
    ['Which gas from air do humans use in respiration?', 'Oxygen', 'Helium|Hydrogen|Neon', 'The body uses oxygen in respiration to release energy from food.'],
    ['Which organ removes waste from blood to make urine?', 'Kidney', 'Stomach|Tongue|Ear', 'Kidneys filter blood and produce urine.'],
    ['Which animal breathes using gills?', 'Fish', 'Cat|Bird|Whale', 'Fish use gills to obtain oxygen from water.'],
    ['Which animal has a backbone?', 'Cat', 'Earthworm|Butterfly|Snail', 'A cat is a vertebrate, an animal with a backbone.'],
    ['A seedling shoot often bends towards what?', 'Light', 'A loud bell|A plastic toy|A stone', 'Shoots respond to light by growing towards it.'],
    ['What do green plants make during photosynthesis?', 'Food', 'Plastic|Metal|Glass', 'Green plants use light energy to make food from water and carbon dioxide.'],
    ['Which travels in straight lines through clear air?', 'Light', 'A crawling snail|A winding river|A growing root', 'Light travels in straight lines in a uniform transparent medium.'],
    ['Which surface reflects a clear image?', 'Smooth mirror', 'Rough cloth|Crushed paper|Grass', 'A smooth mirror reflects light regularly to form an image.'],
    ['What produces sound in a plucked guitar string?', 'Vibration', 'Rust|Freezing|A shadow', 'The vibrating string makes surrounding air vibrate.'],
    ['Which is a renewable energy source?', 'Sunlight', 'Coal|Petroleum|Natural gas', 'Sunlight is naturally replenished; fossil fuels take a very long time to form.'],
    ['A moving bicycle has which form of energy?', 'Kinetic energy', 'Only stored chemical energy|Only light energy|No energy', 'Kinetic energy is the energy of motion.'],
    ['A lamp changes electrical energy mainly into what?', 'Light and heat', 'Food and water|Soil and air|Magnet and seed', 'A lamp produces light and also releases heat.'],
    ['Which habit saves electricity?', 'Switch off unused lights', 'Leave all lights on|Keep the fridge door open|Run an empty washing machine', 'Switching off unused lights reduces energy use.'],
    ['To investigate shadows, which factor should change at a time?', 'Only the factor being tested', 'Every factor|No recorded factor|All objects and lights together', 'Changing one factor lets you connect it to the observed effect.'],
  ],
  5: [
    ['Which structure supports the human body?', 'Skeleton', 'Skin colour|Hair|Saliva', 'The skeleton supports the body and protects organs.'],
    ['What pumps blood around the body?', 'Heart', 'Stomach|Lungs alone|Teeth', 'The heart pumps blood through blood vessels.'],
    ['Why do some fruits have hooks?', 'To attach to animals for dispersal', 'To make electricity|To breathe underwater|To become rocks', 'Hooks can catch on fur and carry seeds away from the parent plant.'],
    ['Which seed feature helps wind dispersal?', 'Light wings or hairs', 'Heavy metal shell|Strong glue|A large stone inside', 'Light wings or hairs help seeds travel in moving air.'],
    ['In a series circuit, one bulb breaks. What happens to the other bulb?', 'It goes out', 'It always gets brighter|It turns blue|It becomes a battery', 'A broken bulb opens the single path in a series circuit.'],
    ['A parallel circuit has how many possible current paths?', 'More than one', 'No path|Exactly zero|Only one always', 'Parallel branches provide more than one path.'],
    ['Which unit is commonly used for temperature in school?', 'Degrees Celsius', 'Centimetres|Litres|Kilograms', 'Temperature can be measured in degrees Celsius using a thermometer.'],
    ['Heat flows naturally from which object to which?', 'Hotter to colder', 'Colder to hotter only|Smaller to larger always|Blue to red always', 'Heat transfers from a hotter object to a colder one.'],
    ['What is ice changing into water called?', 'Melting', 'Freezing|Condensation|Rusting', 'Melting changes a solid into a liquid as it gains heat.'],
    ['What is liquid water changing into water vapour called?', 'Evaporation', 'Freezing|Rusting|Melting', 'Evaporation changes liquid water into a gas.'],
    ['Water droplets outside a cold glass form by which process?', 'Condensation', 'Melting glass|Rusting|Freezing the air', 'Water vapour in the air cools and condenses into liquid droplets.'],
    ['Which two conditions help an iron nail rust?', 'Water and air', 'Light and sound only|Dry sand and darkness|Plastic and cloth', 'Iron rusts when exposed to water and oxygen in air.'],
    ['How does painting an iron gate help prevent rust?', 'It blocks contact with air and water', 'It changes iron into wood|It makes oxygen|It adds water', 'An intact paint layer protects iron from air and water.'],
    ['Which state of matter has a fixed shape?', 'Solid', 'Liquid|Gas|Water vapour', 'A solid keeps its own shape under ordinary conditions.'],
    ['Why does the Moon appear bright?', 'It reflects sunlight', 'It is a burning star|It is made of lamps|It produces its own sunlight', 'We see sunlight reflected from the Moon.'],
  ],
  6: [
    ['Which tool reveals many tiny microorganisms?', 'Microscope', 'Ruler|Measuring jug|Stopwatch', 'A microscope magnifies organisms too small to see clearly with our eyes.'],
    ['Which microorganism helps bread dough rise?', 'Yeast', 'Earthworm|Ant|Grasshopper', 'Yeast produces carbon dioxide gas that makes dough expand.'],
    ['Why does keeping food cold help it last longer?', 'It slows many microorganisms', 'It kills every microorganism instantly|It adds sunlight|It changes food into metal', 'Low temperatures slow the growth of many microorganisms; food still needs safe storage.'],
    ['How does drying help preserve food?', 'It removes water needed by many microorganisms', 'It adds germs|It makes food alive|It adds rain', 'Removing water makes conditions less suitable for many microorganisms.'],
    ['Which is an example of competition?', 'Two seedlings needing the same limited light', 'A stone beside a spoon|Rain falling into the sea|A mirror reflecting a lamp', 'Living things compete when they need the same limited resource.'],
    ['Which action helps conserve wildlife?', 'Protect natural habitats', 'Destroy nesting areas|Pollute rivers|Hunt endangered animals', 'Protecting habitats helps animals find food, shelter and places to reproduce.'],
    ['A force can be described as what?', 'A push or a pull', 'Only a colour|Only a smell|A unit of time', 'A force is a push or a pull acting on an object.'],
    ['What can a force change about a moving ball?', 'Its speed or direction', 'Its material into gold|Its age backwards|Its name only', 'Forces can speed up, slow down or change the direction of motion.'],
    ['Which force opposes sliding between surfaces?', 'Friction', 'Sunlight|Evaporation|Condensation', 'Friction opposes relative motion between contacting surfaces.'],
    ['Why do shoe soles have grooves?', 'To improve grip', 'To remove all friction|To produce light|To make shoes float in air', 'Grooves help the soles grip the ground and reduce slipping.'],
    ['Which usually reduces friction in machine parts?', 'Lubricating oil', 'Extra rough sand|Dry grit|Rust', 'A suitable lubricant reduces rubbing between moving surfaces.'],
    ['Two cyclists travel the same distance. Who has the greater average speed?', 'The one taking less time', 'The one taking more time|Both must be equal|The one with a red bicycle', 'Average speed is distance divided by time. Less time for the same distance means greater speed.'],
    ['Which is a suitable speed unit?', 'Metres per second', 'Metres only|Seconds only|Litres', 'Speed describes distance travelled per unit of time.'],
    ['Why should recyclable materials be sorted?', 'Different materials need different processing', 'Sorting creates more rubbish|All materials are identical|Sorting removes their mass', 'Sorting helps materials such as paper, metal and glass enter suitable recycling processes.'],
    ['Which reduces waste at its source?', 'Carry a reusable bottle', 'Buy a new disposable bottle each hour|Throw clean paper away|Use extra packaging', 'Reusing a bottle reduces the number of disposable bottles needed.'],
  ],
};

export const languagePractice = {
  2: {
    bi: [
      ['Choose: She ___ a red bag.', 'has', 'have|having|are', 'Use has with she.'],
      ['Choose: Two ___ are on the mat.', 'cats', 'cat|cates|catting', 'Two needs the plural noun cats.'],
      ['Choose the opposite of hot.', 'Cold', 'Warm|Red|Sunny', 'Cold is the opposite of hot.'],
      ['Choose: I wash my hands ___ eating.', 'before', 'under|between|inside', 'Before tells us washing happens earlier than eating.'],
      ['Which word names a colour?', 'Green', 'Jump|Chair|Quickly', 'Green is a colour.'],
      ['Choose: The birds ___ flying.', 'are', 'is|am|was', 'Use are with the plural subject birds.'],
      ['Choose: A fish can ___.', 'swim', 'write|read|cook', 'A fish moves through water by swimming.'],
      ['Choose the correct greeting in the morning.', 'Good morning', 'Good night|Goodbye forever|Happy birthday', 'Good morning is a greeting used in the morning.'],
      ['Choose: My brother and I ___ happy.', 'are', 'is|am|has', 'My brother and I means we, so use are.'],
      ['Choose: I can see with my ___.', 'eyes', 'ears|knees|feet', 'Eyes are the body parts used for seeing.'],
      ['Choose: One child, three ___.', 'children', 'childs|childes|child', 'The plural of child is children.'],
      ['Choose: The bag is not heavy. It is ___.', 'light', 'loud|tall|long', 'Light means not heavy in this sentence.'],
    ],
    bm: [
      ['Pilih: Adik ___ air.', 'minum', 'tidur|lari|terbang', 'Kata kerja minum sesuai dengan air.'],
      ['Apakah lawan bagi perkataan panjang?', 'Pendek', 'Tinggi|Besar|Luas', 'Panjang berlawanan maksud dengan pendek.'],
      ['Pilih penjodoh bilangan: se___ pensel.', 'batang', 'ekor|orang|biji', 'Penjodoh bilangan untuk pensel ialah batang.'],
      ['Pilih: Buku itu ada ___ atas meja.', 'di', 'ke|dari|kepada', 'Kata sendi di menunjukkan tempat.'],
      ['Yang manakah kata nama haiwan?', 'Kucing', 'Kerusi|Berlari|Merah', 'Kucing ialah nama haiwan.'],
      ['Pilih tanda baca untuk ayat tanya.', '?', '.|,|:', 'Tanda soal mengakhiri ayat tanya.'],
      ['Pilih: Ali membaca ___ di perpustakaan.', 'buku', 'air|kasut|nasi', 'Buku ialah bahan bacaan.'],
      ['Apakah lawan bagi perkataan siang?', 'Malam', 'Pagi|Petang|Tengah hari', 'Siang berlawanan maksud dengan malam.'],
      ['Pilih penjodoh bilangan: tiga ___ kucing.', 'ekor', 'orang|batang|helai', 'Ekor digunakan untuk haiwan seperti kucing.'],
      ['Pilih: ___ nama kamu?', 'Siapakah', 'Bilakah|Berapakah|Mengapakah', 'Siapakah digunakan untuk bertanya tentang nama atau orang.'],
      ['Yang manakah nama tempat belajar?', 'Sekolah', 'Bantal|Sudu|Kasut', 'Sekolah ialah tempat murid belajar.'],
      ['Pilih: Baju yang dibasuh itu sudah tidak basah. Baju itu ___.', 'kering', 'lapar|pahit|bising', 'Kering bermaksud tidak basah.'],
    ],
  },
  4: {
    bi: [
      ['Choose: Yesterday, Amir ___ to the park.', 'walked', 'walk|walking|walks', 'Yesterday signals the past. The past tense is walked.'],
      ['Choose: This box is ___ than that one.', 'heavier', 'heaviest|heavy|heavily', 'Use the comparative heavier to compare two boxes.'],
      ['Choose: There is ___ milk in the jug.', 'some', 'many|a few|an', 'Milk is uncountable, so some is suitable here.'],
      ['Choose: We stayed indoors ___ it was raining.', 'because', 'but|or|unless', 'Because introduces the reason for staying indoors.'],
      ['Choose the adverb: The turtle moved slowly.', 'slowly', 'turtle|moved|The', 'Slowly tells us how the turtle moved.'],
      ['Choose: These books belong to us. They are ___.', 'ours', 'our|us|we', 'Ours is the possessive pronoun used without a following noun.'],
      ['Choose: Last night, we ___ a film.', 'watched', 'watch|watches|watching', 'Last night places the action in the past, so use watched.'],
      ['Choose: Please speak ___. The baby is sleeping.', 'quietly', 'loud|noisy|quieter than', 'Quietly is an adverb describing how to speak softly.'],
      ['Choose: I was hungry, ___ I ate a sandwich.', 'so', 'but|although|unless', 'So introduces the result of being hungry.'],
      ['Choose: The pencil is ___ than the ruler.', 'shorter', 'shortest|short|shortly', 'Than signals a comparison between two objects.'],
      ['Choose: ___ did you put the keys? On the shelf.', 'Where', 'Who|When|Why', 'Where asks about a place, such as on the shelf.'],
      ['Choose: Mei and Sara made the cards ___.', 'themselves', 'herself|himself|itself', 'The plural subject takes the reflexive pronoun themselves.'],
    ],
    bm: [
      ['Pilih kata sendi yang menunjukkan penerima: Hadiah ini ___ ibu.', 'untuk', 'dari|di|ke', 'Untuk menunjukkan tujuan atau penerima sesuatu.'],
      ['Pilih penjodoh bilangan: dua ___ roti.', 'keping', 'ekor|orang|batang', 'Keping sesuai untuk hirisan roti.'],
      ['Apakah maksud bekerjasama?', 'Melakukan kerja bersama-sama', 'Bekerja seorang diri|Berhenti bekerja|Bermain sepanjang masa', 'Bekerjasama bermaksud melakukan sesuatu bersama-sama.'],
      ['Pilih: Jalan itu licin ___ hujan turun.', 'kerana', 'atau|tetapi|sambil', 'Kerana menghubungkan keadaan dengan sebabnya.'],
      ['Yang manakah kata adjektif dalam ayat Rumah itu besar?', 'besar', 'Rumah|itu|Rumah itu', 'Besar menerangkan sifat rumah.'],
      ['Pilih ejaan yang betul.', 'tanggungjawab', 'tanggung jawab|tangungjawab|tanggungjawap', 'Tanggungjawab ialah kata majmuk mantap yang dieja serangkai.'],
      ['Pilih: Kami bertolak ___ rumah pada pukul tujuh.', 'dari', 'daripada|kepada|oleh', 'Dari digunakan untuk menyatakan tempat asal.'],
      ['Pilih kata tanya: ___ harga buku ini?', 'Berapakah', 'Siapakah|Di manakah|Bilakah', 'Berapakah digunakan untuk bertanya tentang jumlah atau harga.'],
      ['Apakah lawan bagi perkataan rajin?', 'Malas', 'Cergas|Tekun|Pantas', 'Rajin berlawanan maksud dengan malas.'],
      ['Pilih: Ibu memotong sayur dengan ___.', 'pisau', 'bantal|kasut|payung', 'Pisau ialah alat yang digunakan untuk memotong.'],
      ['Pilih ayat perintah yang meminta seseorang duduk.', 'Sila duduk.', 'Saya sudah duduk.|Di manakah kerusi?|Kerusi itu biru.', 'Sila duduk ialah ayat perintah berbentuk permintaan sopan.'],
      ['Pilih: Abang membaca buku ___ adik melukis.', 'manakala', 'kerana itu|demi|hingga ke', 'Manakala menghubungkan dua perbuatan oleh orang yang berlainan.'],
    ],
  },
  5: {
    bi: [
      ['Choose: If it rains, we ___ stay indoors.', 'will', 'would have|had|were', 'Use will for this possible future result.'],
      ['Choose: You ___ wear a helmet when cycling for safety.', 'should', 'should not|cannot|never', 'Should gives advice about wearing a helmet.'],
      ['Choose: This is the ___ tree in our garden.', 'tallest', 'taller|tall|tallness', 'The superlative tallest compares the tree with all others in the garden.'],
      ['Choose: The girl ___ won the race is my friend.', 'who', 'where|when|whose', 'Who refers to the girl and introduces information about her.'],
      ['Choose the word closest in meaning to enormous.', 'Huge', 'Tiny|Quiet|Narrow', 'Enormous means very large or huge.'],
      ['Choose: There are ___ apples than oranges.', 'fewer', 'less|much|little', 'Use fewer with countable plural nouns such as apples.'],
      ['Choose: We ___ finished our homework already.', 'have', 'has|are|were', 'We takes have in this present perfect sentence.'],
      ['Choose: You ___ touch that hot pan.', 'must not', 'must always|should certainly|need to', 'Must not expresses a strong instruction against touching the hot pan.'],
      ['Choose: The boy ___ bicycle is blue is my cousin.', 'whose', 'who|where|when', 'Whose shows that the bicycle belongs to the boy.'],
      ['Choose: There is not ___ sugar left.', 'much', 'many|a few|several', 'Sugar is uncountable, so much is suitable in this negative sentence.'],
      ['Choose the word closest in meaning to exhausted.', 'Very tired', 'Very noisy|Very tidy|Very early', 'Exhausted means extremely tired.'],
      ['Choose: While I was reading, the phone ___.', 'rang', 'ring|ringing|rings yesterday', 'Rang is the past action that happened during the reading.'],
    ],
    bm: [
      ['Apakah maksud ringan tulang?', 'Rajin membantu', 'Malas bekerja|Suka tidur|Cepat marah', 'Ringan tulang ialah simpulan bahasa bagi orang yang rajin membantu.'],
      ['Pilih: Surat itu ditulis ___ Aina.', 'oleh', 'ke|di|untuk ke', 'Oleh memperkenalkan pelaku dalam ayat pasif ini.'],
      ['Pilih: Ibu membeli sayur ___ ikan.', 'dan', 'kerana|walaupun|sambil', 'Dan menggabungkan dua benda yang dibeli.'],
      ['Apakah kata dasar bagi permainan?', 'main', 'permain|per|mainan sahaja', 'Permainan terbentuk daripada kata dasar main dengan apitan per-...-an.'],
      ['Pilih kata ganda yang bermaksud banyak buku.', 'buku-buku', 'berbuku|bukuan|membuku', 'Penggandaan buku-buku menunjukkan bilangan yang banyak.'],
      ['Pilih: Walaupun penat, Farah ___ menyiapkan tugas.', 'tetap', 'belum pernah|mustahil|tidak mungkin', 'Tetap menunjukkan Farah meneruskan usaha walaupun penat.'],
      ['Apakah maksud buah tangan?', 'Hadiah yang dibawa ketika berkunjung', 'Buah yang tumbuh pada tangan|Tangan yang sakit|Alat berkebun', 'Buah tangan ialah hadiah untuk orang yang dikunjungi.'],
      ['Pilih: Cikgu menghadiahkan buku ___ pemenang.', 'kepada', 'di|dari|ke dalam', 'Kepada menunjukkan orang yang menerima buku.'],
      ['Pilih kata adjektif: Sup itu terlalu ___.', 'masin', 'berlari|meja|mereka', 'Masin ialah kata adjektif rasa yang boleh menerangkan sup.'],
      ['Pilih: Kita perlu berjimat ___ tidak membazir.', 'supaya', 'walaupun|sambil|tetapi', 'Supaya menyatakan tujuan kita berjimat.'],
      ['Apakah kata dasar bagi kebersihan?', 'bersih', 'kebersih|sihan|ber', 'Kebersihan dibentuk dengan apitan ke-...-an pada kata dasar bersih.'],
      ['Pilih ayat yang menggunakan tanda koma dengan betul.', 'Saya membeli pensel, buku dan pemadam.', 'Saya membeli, pensel buku dan pemadam.|Saya, membeli pensel buku dan pemadam.|Saya membeli pensel buku dan, pemadam.', 'Koma memisahkan unsur dalam senarai sebelum unsur terakhir yang dihubungkan dengan dan.'],
    ],
  },
  6: {
    bi: [
      ['Choose: The bridge ___ by the villagers last year.', 'was built', 'build|is building|were built', 'The singular bridge takes was in this past passive sentence.'],
      ['Choose: I have lived here ___ 2020.', 'since', 'for|during of|until ago', 'Since introduces the starting point of a period continuing to now.'],
      ['Choose: Neither of the answers ___ correct.', 'is', 'are|were|be', 'In formal usage, neither takes the singular verb is.'],
      ['Choose: Although the task was difficult, she ___.', 'kept trying', 'because she left|but tired|and difficult', 'Kept trying completes a main clause contrasting with the difficulty.'],
      ['Choose the best connector: We saved water; ___, our usage fell.', 'therefore', 'however|instead of|although', 'Therefore introduces a result.'],
      ['Choose the sentence with correct punctuation.', 'Where is my book?', 'Where is my book.|where is my book?|Where is my book,', 'A question starts with a capital and ends with a question mark.'],
      ['Choose: By the time we arrived, the bus ___ left.', 'had', 'has|is|does', 'Had left shows an action completed before another past event.'],
      ['Choose: This problem can ___ by working together.', 'be solved', 'solving|solves|been solve', 'A modal passive uses can plus be plus a past participle.'],
      ['Choose: The museum, ___ we visited yesterday, was fascinating.', 'which', 'who|whose|when', 'Which refers to the museum as the object of visited.'],
      ['Choose: She practised daily ___ improve her skills.', 'in order to', 'because of|despite|although', 'In order to introduces the purpose of practising.'],
      ['Choose the most suitable formal request.', 'Could you please explain this step?', 'Explain it now!|You explain this!|Explain, explain!', 'Could you please makes a polite request.'],
      ['Choose: Unless you water the seedlings, they ___ dry out.', 'will', 'had|was|having', 'Unless means if not; will describes the possible future result.'],
    ],
    bm: [
      ['Apakah maksud bagai aur dengan tebing?', 'Saling membantu', 'Saling bermusuh|Hidup sendirian|Membazir masa', 'Peribahasa ini menggambarkan hubungan saling membantu.'],
      ['Pilih ayat pasif yang betul bagi Saya membaca buku itu.', 'Buku itu saya baca.', 'Buku itu saya membaca.|Saya dibaca buku itu.|Buku membaca saya.', 'Dengan kata ganti diri pertama, kata kerja pasif hadir tanpa imbuhan di-.'],
      ['Pilih: Cadangan itu lebih baik ___ cadangan sebelumnya.', 'daripada', 'dari|di|ke', 'Daripada digunakan untuk perbandingan.'],
      ['Pilih penanda wacana untuk menyatakan kesimpulan.', 'Kesimpulannya', 'Sebagai contoh|Pertama sekali|Selain itu', 'Kesimpulannya memperkenalkan rumusan.'],
      ['Apakah maksud lestari?', 'Kekal terpelihara', 'Cepat musnah|Sentiasa rosak|Tidak berguna', 'Lestari merujuk keadaan yang kekal atau terpelihara.'],
      ['Pilih ejaan kata majmuk yang betul.', 'kereta api', 'keretaapi|kereta-api|kereta Api', 'Kereta api ialah kata majmuk yang dieja terpisah.'],
      ['Apakah maksud sediakan payung sebelum hujan?', 'Bersedia sebelum ditimpa kesusahan', 'Hanya keluar ketika hujan|Membeli payung setiap hari|Menunggu masalah berlaku', 'Peribahasa ini menasihati kita supaya bersedia menghadapi kemungkinan buruk.'],
      ['Pilih: Usaha itu ___ meningkatkan kebersihan sekolah.', 'bertujuan untuk', 'walaupun|daripada|sambil kepada', 'Bertujuan untuk menyatakan matlamat sesuatu usaha.'],
      ['Pilih pasangan kata hubung yang betul.', 'Bukan sahaja rajin, malah baik hati.', 'Bukan sahaja rajin, kerana baik hati.|Bukan sahaja rajin, jika baik hati.|Bukan sahaja rajin, supaya baik hati.', 'Bukan sahaja berpasangan dengan malah untuk menambah maklumat.'],
      ['Pilih ayat yang tepat untuk surat rasmi.', 'Kerjasama pihak tuan amat dihargai.', 'Kau tolonglah cepat!|Hei, buat sekarang!|Aku nak benda itu.', 'Surat rasmi menggunakan bahasa yang sopan dan formal.'],
      ['Apakah maksud berdikari?', 'Berusaha dengan kemampuan sendiri', 'Sentiasa menyalahkan orang|Menunggu bantuan sahaja|Mengelakkan semua tugas', 'Berdikari bermaksud berusaha tanpa terlalu bergantung pada orang lain.'],
      ['Pilih: Murid itu yakin ___ kebolehannya.', 'akan', 'dari|di|ke', 'Kata adjektif yakin boleh diikuti kata sendi akan untuk melengkapkan maksud.'],
    ],
  },
};
